In [142]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder

data = pd.read_csv('Sales_masked.csv')
print(data.keys())
# data.isnull().sum().to_frame()
data.sort_values('DayKey', inplace=True)

data_np = data.to_numpy()
data_np

keep_le = []

def gen_GAC():
    gen_G =[]
    for i in range(1,11):
        gen_G.append('G'+str(i%11))
    gen_A =[]
    for i in range(1,7):
        gen_A.append('A'+str(i%7))
    gen_C =[]
    for i in range(1,3):
        gen_C.append('C'+str(i%3))

    string = []
    for i in range(10):
        for j in range(12):
            string.append(gen_G[i]+gen_A[j%6])
    sum =0
    count = 1
    for i in range(120):
        if sum < 6   :
            string[i] += 'C'+'1'
            sum +=1
        else :
            string[i] += 'C'+'2'
            sum +=1
            if sum == 12 :
                sum = 0
    return string
# หาindex 
def findrecode(product, area, chanel):
        row = 0
        pac = gen_GAC()
        for i in range(len(pac)):
            if len(pac[i]) > 6 :
                if pac[i][0:3] == product and pac[i][3:5] == area and pac[i][5:] == chanel: #แก้ตรงนี้
                    row = i
                    break
            else :
                if pac[i][0:2] == product and pac[i][2:4] == area and pac[i][4:] == chanel: #แก้ตรงนี้
                    row = i
                    break
        return row

sum=0
def transform_d(G,check=False,product=None,area=None,chanel=None):
    if check != True:
        global sum
        for i in range(4):
            le = LabelEncoder()
            keep_le.append(le)
            G[:, i] = keep_le[sum].fit_transform(G[:, i])
            sum += 1
    else:
        index = findrecode(product, area, chanel) #หาข้อมูลตำแน่งที่ต้องการ จะเปลี่ยนว่าจะไป อยู่ในตัวใดจาก 120 ตัว
        # print(index)
        for i in range(G.shape[1]-2):
            G[:,i] = keep_le[int(arr[index][i])].fit_transform(G[:,i])

# สำหรับอ้างอิงตำแหน่งใน keep_le
arr = np.zeros((120, 4))
xum = 0
for i in range(120):
    for j in range(4):
        arr[i][j] += xum
        xum += 1
        
# print(arr)

# #product group 1 Area 1 channel 1
def identifier(product, area, chanel):
    G = []
    for i in range(data_np.shape[0]):
        if data_np[i, 1] == product and data_np[i, 2] == area and data_np[i, 3] == chanel:
            G.append(data_np[i, :])
    G = np.array(G)
    transform_d(G)  # problem
    return G



Index(['DayKey', 'ProductGroup', 'Area', 'Channel', 'Sales', 'CumSales'], dtype='object')


In [143]:
# print(len(keep_le)) #เช็คตำนวน encode

# Good
def get_inverse(G,index):
    xx = []
    for i in range(G.shape[0]):
        xx.append(G[i,index])
    return xx

# not yet
def inverse_d(G,product, area, chanel):
    # print(product, area, chanel)
    index = findrecode(product, area, chanel) #หาข้อมูลตำแน่งที่ต้องการ จะเปลี่ยนว่าจะไป อยู่ในตัวใดจาก 120 ตัว
    # print(index)
    for i in range(G.shape[1]-2): # columns - 2 
        xx = get_inverse(G,i) # เอาข้อมูลจาก ฟังก์ชันมาแปลง กลับ เป็นตัวเดิม
        # print(xx)
        G[:,i] = keep_le[int(arr[index][i])].inverse_transform(xx)


In [144]:
G111 = identifier('G1','A1','C1')
print(len(keep_le))
inverse_d(G111,'G1','A1','C1')
print(G111)
transform_d(G111,True,'G1','A1','C1')
print(G111)

4
[['2010-01-02' 'G1' 'A1' 'C1' 10794 10794.0]
 ['2010-01-04' 'G1' 'A1' 'C1' 5397 16191.0]
 ['2010-01-05' 'G1' 'A1' 'C1' 2878 19069.0]
 ...
 ['2022-05-29' 'G1' 'A1' 'C1' 14955 3583821.0]
 ['2022-05-30' 'G1' 'A1' 'C1' 252557 3836378.0]
 ['2022-05-31' 'G1' 'A1' 'C1' 198318 4034696.0]]
[[0 0 0 0 10794 10794.0]
 [1 0 0 0 5397 16191.0]
 [2 0 0 0 2878 19069.0]
 ...
 [3829 0 0 0 14955 3583821.0]
 [3830 0 0 0 252557 3836378.0]
 [3831 0 0 0 198318 4034696.0]]


In [145]:
print(len(keep_le))
inverse_d(G111,'G1','A1','C1')
print(G111)
transform_d(G111,True,'G1','A1','C1')
print(G111)

4
[['2010-01-02' 'G1' 'A1' 'C1' 10794 10794.0]
 ['2010-01-04' 'G1' 'A1' 'C1' 5397 16191.0]
 ['2010-01-05' 'G1' 'A1' 'C1' 2878 19069.0]
 ...
 ['2022-05-29' 'G1' 'A1' 'C1' 14955 3583821.0]
 ['2022-05-30' 'G1' 'A1' 'C1' 252557 3836378.0]
 ['2022-05-31' 'G1' 'A1' 'C1' 198318 4034696.0]]
[[0 0 0 0 10794 10794.0]
 [1 0 0 0 5397 16191.0]
 [2 0 0 0 2878 19069.0]
 ...
 [3829 0 0 0 14955 3583821.0]
 [3830 0 0 0 252557 3836378.0]
 [3831 0 0 0 198318 4034696.0]]


In [146]:
#group 1

# G111 = identifier('G1','A1','C1')

# G121 = identifier('G1','A2','C1')

# G131= identifier('G1','A3','C1')

# G141 = identifier('G1','A4','C1')

# G151 = identifier('G1','A5','C1')

# G161 = identifier('G1','A6','C1')

# G112 = identifier('G1','A1','C2')

# G122 = identifier('G1','A2','C2')

# G132 = identifier('G1','A3','C2')

# G142 = identifier('G1','A4','C2')

# G152 = identifier('G1','A5','C2')

# G162 = identifier('G1','A6','C2')




In [147]:
#Group 2 
# G211 = identifier('G2','A1','C1')

# G221 = identifier('G2','A2','C1')

# G231= identifier('G2','A3','C1')

# G241 = identifier('G2','A4','C1')

# G251 = identifier('G2','A5','C1')

# G261 = identifier('G2','A6','C1')

# G212 = identifier('G2','A1','C2')

# G222 = identifier('G2','A2','C2')

# G232 = identifier('G2','A3','C2')

# G242 = identifier('G2','A4','C2')

# G252 = identifier('G2','A5','C2')

# G262 = identifier('G2','A6','C2')

In [148]:

# #Group 3 
# G311 = identifier('G3','A1','C1')
# transform_d(G311)
# G321 = identifier('G3','A2','C1')
# transform_d(G321)
# G331= identifier('G3','A3','C1')
# transform_d(G331)
# G341 = identifier('G3','A4','C1')
# transform_d(G341)
# G351 = identifier('G3','A5','C1')
# transform_d(G351)
# G361 = identifier('G3','A6','C1')
# transform_d(G361)
# G312 = identifier('G3','A1','C2')
# transform_d(G312)
# G322 = identifier('G3','A2','C2')
# transform_d(G322)
# G332 = identifier('G3','A3','C2')
# transform_d(G132)
# G342 = identifier('G3','A4','C2')
# transform_d(G342)
# G352 = identifier('G3','A5','C2')
# transform_d(G352)
# G362 = identifier('G3','A6','C2')
# transform_d(G362)

In [149]:
# #Group 4 
# G411 = identifier('G4','A1','C1')
# transform_d(G411)
# G421 = identifier('G4','A2','C1')
# transform_d(G421)
# G431= identifier('G4','A3','C1')
# transform_d(G431)
# G441 = identifier('G4','A4','C1')
# transform_d(G441)
# G451 = identifier('G4','A5','C1')
# transform_d(G451)
# G461 = identifier('G4','A6','C1')
# transform_d(G461)
# G412 = identifier('G4','A1','C2')
# transform_d(G412)
# G422 = identifier('G4','A2','C2')
# transform_d(G422)
# G432 = identifier('G4','A3','C2')
# transform_d(G432)
# G442 = identifier('G4','A4','C2')
# transform_d(G442)
# G452 = identifier('G4','A5','C2')
# transform_d(G452)
# G462 = identifier('G4','A6','C2')
# transform_d(G462)

In [150]:
# #Group 5
# G511 = identifier('G5','A1','C1')
# transform_d(G511)
# G521 = identifier('G5','A2','C1')
# transform_d(G521)
# G531= identifier('G5','A3','C1')
# transform_d(G531)
# G541 = identifier('G5','A4','C1')
# transform_d(G541)
# G551 = identifier('G5','A5','C1')
# transform_d(G551)
# G561 = identifier('G5','A6','C1')
# transform_d(G561)
# G512 = identifier('G5','A1','C2')
# transform_d(G512)
# G522 = identifier('G5','A2','C2')
# transform_d(G522)
# G532 = identifier('G5','A3','C2')
# transform_d(G532)
# G542 = identifier('G5','A4','C2')
# transform_d(G542)
# G552 = identifier('G5','A5','C2')
# transform_d(G552)
# G562 = identifier('G5','A6','C2')
# transform_d(G562)

In [151]:
# #Group 6
# G611 = identifier('G6','A1','C1')
# transform_d(G611)
# G621 = identifier('G6','A2','C1')
# transform_d(G621)
# G631= identifier('G6','A3','C1')
# transform_d(G631)
# G641 = identifier('G6','A4','C1')
# transform_d(G641)
# G651 = identifier('G6','A5','C1')
# transform_d(G651)
# G661 = identifier('G6','A6','C1')
# transform_d(G661)
# G612 = identifier('G6','A1','C2')
# transform_d(G612)
# G622 = identifier('G6','A2','C2')
# transform_d(G622)
# G632 = identifier('G6','A3','C2')
# transform_d(G632)
# G642 = identifier('G6','A4','C2')
# transform_d(G642)
# G652 = identifier('G6','A5','C2')
# transform_d(G652)
# G662 = identifier('G6','A6','C2')
# transform_d(G662)

In [152]:
# #group 7 
# G711 = identifier('G7','A1','C1')
# transform_d(G711)
# G721 = identifier('G7','A2','C1')
# transform_d(G721)
# G731= identifier('G7','A3','C1')
# transform_d(G731)
# G741 = identifier('G7','A4','C1')
# transform_d(G741)
# G751 = identifier('G7','A5','C1')
# transform_d(G751)
# G761 = identifier('G7','A6','C1')
# transform_d(G761)
# G712 = identifier('G7','A1','C2')
# transform_d(G712)
# G722 = identifier('G7','A2','C2')
# transform_d(G722)
# G732 = identifier('G7','A3','C2')
# transform_d(G732)
# G742 = identifier('G7','A4','C2')
# transform_d(G742)
# G752 = identifier('G7','A5','C2')
# transform_d(G752)
# G762 = identifier('G7','A6','C2')
# transform_d(G762)

In [153]:
# #group 8
# G811 = identifier('G8','A1','C1')
# transform_d(G811)
# G821 = identifier('G8','A2','C1')
# transform_d(G821)
# G831= identifier('G8','A3','C1')
# transform_d(G831)
# G841 = identifier('G8','A4','C1')
# transform_d(G841)
# G851 = identifier('G8','A5','C1')
# transform_d(G851)
# G861 = identifier('G8','A6','C1')
# transform_d(G861)
# G812 = identifier('G8','A1','C2')
# transform_d(G812)
# G822 = identifier('G8','A2','C2')
# transform_d(G822)
# G832 = identifier('G8','A3','C2')
# transform_d(G832)
# G842 = identifier('G8','A4','C2')
# transform_d(G842)
# G852 = identifier('G8','A5','C2')
# transform_d(G852)
# G862 = identifier('G8','A6','C2')
# transform_d(G862)

In [154]:
# #group 9
# G911 = identifier('G9','A1','C1')
# transform_d(G911)
# G921 = identifier('G9','A2','C1')
# transform_d(G921)
# G931= identifier('G9','A3','C1')
# transform_d(G931)
# G941 = identifier('G9','A4','C1')
# transform_d(G941)
# G951 = identifier('G9','A5','C1')
# transform_d(G951)
# G961 = identifier('G9','A6','C1')
# transform_d(G961)
# G912 = identifier('G9','A1','C2')
# transform_d(G912)
# G922 = identifier('G9','A2','C2')
# transform_d(G922)
# G932 = identifier('G9','A3','C2')
# transform_d(G932)
# G942 = identifier('G9','A4','C2')
# transform_d(G942)
# G952 = identifier('G9','A5','C2')
# transform_d(G952)
# G962 = identifier('G9','A6','C2')
# transform_d(G962)

In [155]:
# #group 10
# G1011 = identifier('G10','A1','C1')
# transform_d(G1011)
# G1021 = identifier('G10','A2','C1')
# transform_d(G1021)
# G1031= identifier('G10','A3','C1')
# transform_d(G1031)
# G1041 = identifier('G10','A4','C1')
# transform_d(G1041)
# G1051 = identifier('G10','A5','C1')
# transform_d(G1051)
# G1061 = identifier('G10','A6','C1')
# transform_d(G1061)
# G1012 = identifier('G10','A1','C2')
# transform_d(G1012)
# G1022 = identifier('G10','A2','C2')
# transform_d(G1022)
# G1032 = identifier('G10','A3','C2')
# transform_d(G1032)
# G1042 = identifier('G10','A4','C2')
# transform_d(G1042)
# G1052 = identifier('G10','A5','C2')
# transform_d(G1052)
# G1062 = identifier('G10','A6','C2')
# transform_d(G1062)